FROM ubuntu:16.04

RUN apt-get update 
RUN apt-get install -y apt-utils python-dev python-pip gcc g++ make automake

WORKDIR /var/oasis/ktools
COPY ./ ./
RUN autoreconf
RUN sh ./configure 
RUN make 
RUN make check 
RUN make install
