FROM coreoasis/oasis_base:R_0_0_0_14

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y gcc g++ make libtool automake autoconf zlib1g-dev

WORKDIR /var/oasis/ktools
COPY ./ ./
RUN sh ./autogen.sh; sh ./configure 
RUN make; make check; make install
