#!/bin/sh
SYSNAME=`uname -o`

touch aclocal.m4
touch Makefile.in
touch configure
touch config.h.in

rm -f ktest/cw32bld
rm -f ktest/cw64bld
rm -f ktest/uwbld
 
if [ "$SYSNAME" = "Cygwin" ]; then
   ./configure  --build=x86_64 --host i686-w64-mingw32 --prefix=/cygdrive/c/oasis
   touch ktest/cw32bld
   exit 0
else
   echo "Must run this under cygwin"
fi
