#!/bin/sh
SYSNAME=`uname -o`

touch aclocal.m4
touch Makefile.in
touch config.h.in


rm -f ktest/cw32bld
rm -f ktest/cw62bld
rm -f ktest/uwbld
 
if [ "$SYSNAME" = "Cygwin" ]; then
	# ./configure  --host  i686-w64-mingw32 --prefix=/cygdrive/c/oasis   # do not use 32 bit variant!!!
	#./configure  --build=x86_64 --host x86_64-w64-mingw32 --prefix=/cygdrive/c/oasis   --without-zlib
	./configure  --build=x86_64 --host x86_64-w64-mingw32 --prefix=/cygdrive/c/oasis   --with-zlib=/usr/x86_64-w64-mingw32/sys-root/mingw/
   	touch ktest/cw64bld
   	exit 0
else
   DIST_ID=`lsb_release -i -s`
   if [ "$DIST_ID" = "Ubuntu" ]; then
	./configure  --host x86_64-w64-mingw32 --prefix=/cygdrive/c/oasis
   	touch ktest/uwbld
	exit 0
   fi
   echo "Must run this under cygwin"
fi
