#!/bin/sh
SYSNAME=`uname -o`

touch aclocal.m4
touch Makefile.in
touch configure
touch config.h.in

rm -f ktest/cwbld
rm -f ktest/uwbld
 
if [ "$SYSNAME" = "Cygwin" ]; then
   ./configure  --build=x86_64 --host i686-w64-mingw32 --prefix=/cygdrive/c/oasis
   touch ktest/cwbld
   exit 0
else
   DIST_ID=`lsb_release -i -s`
   if [ "$DIST_ID" = "Ubuntu" ]; then
	./configure  --host x86_64-w64-mingw32 --prefix=/cygdrive/c/oasis
   	touch ktest/uwbld
	exit 0
   fi
   echo "Must run this under cygwin"
fi
