FROM gcc:latest

RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*
WORKDIR /var/ktools
COPY . /var/ktools
COPY ./jenkins/entrypoint_build.sh /usr/local/bin/build.sh

ENTRYPOINT build.sh
