name: compile-ktools
on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: (MacOS) Install dependencies         
      run: |
        ln -s /usr/bin/shasum5.18 /usr/local/bin/sha1sum
        brew install \
            autoconf \
            automake \
            libtool \
            zlib-ng

    - name: (MacOS) Build ktools x86
      run: |
        BIN_TARGET=$(pwd)/x86
        ./autogen.sh
        ./configure --enable-osx --enable-o3 --prefix=$BIN_TARGET
        make check
        make install

    - name: 'Upload Ktool binaries - x86'
      uses: actions/upload-artifact@v2
      with:
        name: Darwin_x86_64
        path: x86/bin
        retention-days: 5
