name: compile-ktools
on: [push]

jobs:
  build-osx:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: (MacOS) Install dependencies
      run: |
        ln -s /usr/bin/shasum5.18 /usr/local/bin/sha1sum
        brew install \
            autoconf \
            automake \
            libtool \
            zlib-ng

    - name: (MacOS) Build ktools x86
      run: |
        BIN_TARGET=$(pwd)/x86
        ./autogen.sh
        ./configure --enable-osx --enable-o3 --prefix=$BIN_TARGET
        make check
        make install

    - name: 'Upload Ktool binaries - x86'
      uses: actions/upload-artifact@v2
      with:
        name: Darwin_x86_64
        path: x86/bin
        retention-days: 5


# https://github.com/docker/build-push-action
# https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md


  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-


#(LOCAL)

    - name: Create ktools-builder
      uses: docker/build-push-action@v3
      with:
        push: false  # push image to remote reg
        load: true   # load docker image as local image
        context: .
        tags: ktools-builder:latest
        file: jenkins/Dockerfile.clang-build
        #outputs: type=docker,dest=/tmp/myimage.tar
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Show images (DEBUG)
      run: |
        docker images

    - name: Build with Autotools
      working-directory: ${{ github.workspace }}
      run: |
        docker run --entrypoint build-autotools.sh -v $(pwd):/var/ktools ktools-builder
        ls ./tar

    - name: Build with Cmake
      working-directory: ${{ github.workspace }}
      run: |
        docker run --entrypoint build-cmake.sh -v $(pwd):/var/ktools ktools-builder
        ls ./tar



#    - name: Build with Autotools
#      uses: addnab/docker-run-action@v3
#      with:
#        image: ktools-builder:latest
#        #shell: bash
#        run: ./build-autotools.sh
#        #options: -v ${{ github.workspace }}:/var/ktools
#
#    - name: Build with Cmake
#      uses: addnab/docker-run-action@v3
#      with:
#        image: ktools-builder:latest
#        #shell: bash
#        options: -v ${{ github.workspace }}:/var/ktools
#        run: ./build-cmake.sh

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
