name: compile-ktools
on: [push]

jobs:
  build-osx:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: (MacOS) Install dependencies
      run: |
        ln -s /usr/bin/shasum5.18 /usr/local/bin/sha1sum
        brew install \
            autoconf \
            automake \
            libtool \
            zlib-ng

    - name: (MacOS) Build ktools x86
      run: |
        BIN_TARGET=$(pwd)/x86
        ./autogen.sh
        ./configure --enable-osx --enable-o3 --prefix=$BIN_TARGET
        make check
        make install

    - name: 'Upload Ktool binaries - x86'
      uses: actions/upload-artifact@v2
      with:
        name: Darwin_x86_64
        path: x86/bin
        retention-days: 5



  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create ktools-builder
      uses: docker/build-push-action@v3
        with:
          push: false
          context: .
          tags: ktools-builder:latest
          file: jenkins/Dockerfile.clang-build
          #outputs: type=docker,dest=/tmp/myimage.tar
