name: compile-ktools

on: [push]

jobs:
  build:
    strategy:
    matrix:
      include:
        - os: macos-latest
#        - os: ubuntu-latest
    defaults:
      run:
        shell: bash
    runs-on: "${{ matrix.os }}"    
    steps:
    - uses: actions/checkout@v2.3.4

    - name: (Ubuntu) Install dependencies  
      if: "${{ runner.os == 'Linux' }}" 
      run: |-
        sudo apt-get install --yes --no-install-recommends -V \
            build-essential \
            libtool \
            zlib1g-dev \
            autoconf \
            clang 

    - name: (MacOS) Install dependencies         
      if: "${{ runner.os == 'macOS' }}"
      run: |
        brew install \
            autoconf \
            automake \
            clang \
            libtool \
            zlib1g-dev


    - name: (MacOS) Build ktools 
      if: "${{ runner.os == 'macOS' }}"
      run: |
        BIN_TARGET=$(pwd)
        TAR_TARGET='Darwin_x86_64.tar.gz'
        ./autogen.sh
        ./configure --enable-osx --enable-o3 --prefix=$BIN_TARGET
        make check
