name: compile-ktools

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2.3.4

#    - name: (Ubuntu) Install dependencies  
#      run: |-
#        sudo apt-get install --yes --no-install-recommends -V \
#            build-essential \
#            libtool \
#            zlib1g-dev \
#            autoconf \
#            clang 

    - name: (MacOS) Install dependencies         
      run: |
        brew install \
            autoconf \
            automake \
            clang \
            libtool \
            zlib1g-dev

    - name: (MacOS) Build ktools 
      run: |
        BIN_TARGET=$(pwd)
        TAR_TARGET='Darwin_x86_64.tar.gz'
        ./autogen.sh
        ./configure --enable-osx --enable-o3 --prefix=$BIN_TARGET
        make check

        
